name: Daily Auto Commit with Telegram

on:
  schedule:
    - cron: '0 12 * * *'  # Каждый день в 12:00 UTC
  workflow_dispatch:
    inputs:
      custom_message:
        description: 'Custom commit message'
        required: false
        default: '🤖 Automated commit'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Run commit bot
      id: commit_bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        python .github/scripts/commit_bot.py
        echo "COMMIT_TIME=$(date -u +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
    
    - name: Commit and push changes
      env:
        COMMIT_MESSAGE: ${{ github.event.inputs.custom_message }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        git add .
        
        if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "$COMMIT_MESSAGE" ]; then
          MSG="$COMMIT_MESSAGE"
        else
          MSG="🤖 Auto-commit: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        fi
        
        # Коммитим только если есть изменения
        git diff --staged --quiet || git commit -m "$MSG"
        git push
    
    - name: Send success notification
      if: success()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python -c "
        import os, requests
        from datetime import datetime
        
        token = os.getenv('TELEGRAM_BOT_TOKEN')
        chat_id = os.getenv('TELEGRAM_CHAT_ID')
        
        if token and chat_id:
            url = f'https://api.telegram.org/bot{token}/sendMessage'
            message = f'''✅ <b>Git Auto-Commit Успешно!</b>

        🎯 <b>Статус:</b> Workflow выполнен
        📅 <b>Время:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        🚀 <b>Репозиторий:</b> ${{ github.repository }}
        🔗 <b>Actions:</b> https://github.com/${{ github.repository }}/actions

        <i>Коммит автоматически создан и отправлен</i>'''
                    
                    requests.post(url, json={
                        'chat_id': chat_id,
                        'text': message,
                        'parse_mode': 'HTML'
                    })
                "
            
            - name: Send failure notification
            if: failure()
            env:
                TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
            run: |
        python -c "
        import os, requests
        from datetime import datetime
        
        token = os.getenv('TELEGRAM_BOT_TOKEN')
        chat_id = os.getenv('TELEGRAM_CHAT_ID')
        
        if token and chat_id:
            url = f'https://api.telegram.org/bot{token}/sendMessage'
            message = f'''❌ <b>Git Auto-Commit Ошибка!</b>

